### ISSUE TITLE
R Project interface with Factory

### ISSUE THREAD

**Issue by nsbatra** [reconverse/reportfactory#81]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x ] I have the most recent version of reportfactory and R
 - [x ] I have found a bug
 - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Hi team, thanks for this great package. 

It is not clear from the vignette or documentation how reportfactory creation should be done in relation to R project creation, nor how to re-enter a factory. It seems as though a factory is intended to be a R project, given it's creation of here(), gitignore, and sub-folders. _Perhaps what is missing is just an R project file when a factory is created?_ Below some observations from my testing:

If I interpret the instructions correctly, I can run new_factory() and create a folder containing the factory anywhere I want. If I run new_factory() from within an R project, the factory folder is created one level within the R project folder. Or, I can use path = and provide another folder folder for the factory to be created in (could be a non-R project folder).  
 
**Within an R project:** 
So, when I create an R project, a factory folder is created within it... and all works OK in that session because move_in = TRUE (default) - the factory is recognized, here() is the root of the factory (not of the surrounding R project), and compiling works. However, if I finish my session and close out... how to re-enter the factory? Naturally I would re-open the R project (click on R project icon). However when I do this I can load reportfactory but the working directory and here() now all point to the R project root - not the root of the factory. Thus, a function like compile_reports() results in "Error: Directory . is not part of a report factory". So how to fix this? How can I "move in" to the factory? set_here() didn't work. My fix was to run the command setwd(here::here("new_factory")), which changed the working directory (but not the here()!). Somehow the reports compiled despite my here() being the R project root. I guess their here() root was the factory. 

**Outside an R project:**  
Again, it's complicated to re-open the factory. To start,I can load reportfactory and add a new factory to a non-R project folder. A factory is created there and I am "moved in" so the factory is validated and I can compile. However, when I close the session, how to get back into the factory? What works is if I have no other RStudio windows open and I navigate via computer's file finder and click open one of the Rmds in report_sources. But I am not clear that others would know to try this approach and may just sputter around wondering how to open the factory. If I have another RStudio window open, of course the Rmd script opens there and the working directory doesn't change and no success. Also if I close all RStudio windows, start a new fresh RStudio window, close out any projects in that window, and then navigate in RStudio Files pane to an Rmd from report_sources and click it open... the working directory does not change and the factory is not recognized. 

---------

**Comment by tjtnew** [comment]
Hi Neale - The `new_factory()` function now defaults to creating a .Rproj file within the base of the factory and, if `move_in = TRUE` with open this project similar to opening a new project in RStudio.  Could you try this out and see if this resolves the issue? Cheers

**Comment by nsbatra** [comment]
With the new Github version of reportfactory, this issue is resolved. Will
this update be on CRAN soon, or when might that occur?
Thank you Tim

**Comment by tjtnew** [comment]
Source on cran now. Binaries should be there in a couple of days.
