### ISSUE TITLE
More informative error message

### ISSUE THREAD

**Issue by nsbatra** [reconverse/reportfactory#82]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x ] I have the most recent version of reportfactory and R
 - [ x] I have found a bug
 - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Suggesting more informative message when user attempts to compile a report that does not exist. Currently says "All Done!" which makes it sound like something worked. 

For example:
- When a non-existant report is provided to reports =, an "All Done!" message is returned - which is confusing because nothing has been compiled.

- Likewise, the option to run all reports in one folder did not seem to work: reports = "folder_name/". This is shown in the first graphic in the README. I again get an "All Done!" message, but nothing has compiled. 

On another note: 
With compile_reports(), if you set reports = "file_name.**rmd**" the compiling does not work. But using a capital R (.**Rmd**) works. It might be worth emphasizing in the README that capitalization matters.

Thanks for your time on this!

---------

**Comment by tjtnew** [comment]
Cheers - good points!  I've fixed the issue with .rmd and .Rmd in the current master branch and will sort the error messages out over the coming days.

**Comment by tjtnew** [comment]
> Likewise, the option to run all reports in one folder did not seem to work: reports = "folder_name/". This is shown in the first graphic in the README. I again get an "All Done!" message, but nothing has compiled.

I've not been able to reproduce this - can you give more details / reprex?

**Comment by tjtnew** [comment]
Have now added better error messaging. Can you try the latest version and let me know if all now fixed.

**Comment by nsbatra** [comment]
Running reports by subfolder folder now seems to work for me. And error
messaging much improved. Thank you Tim
