### ISSUE TITLE
README mistake?

### ISSUE THREAD

**Issue by nsbatra** [reconverse/reportfactory#85]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x ] I have the most recent version of reportfactory and R
 - [ x] I have found a bug
 - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

If the user copies and runs this code directly, the new project is saved to a temporary directory and is not functional. 

![image](https://user-images.githubusercontent.com/52152191/124980914-f5016d80-e002-11eb-8391-ef27cbe90f46.png)
---------

**Comment by TimTaylor** [comment]
Cheers @nsbatra. That's annoying. The description is also wrong as `move_in = TRUE` is the default anyway. Probably will be best to change this to either
```r
new_factory("my_factory", path = getwd())
```
or
```r
new_factory("my_factory")
```
Both are equivalent but the first is maybe a little more explicit for new users understanding what is happening. What do you think?

**Comment by TimTaylor** [comment]
More annoyingly `README.Rmd` file is correct (in terms of commands) but obviously hasn't been reknitted to the `README.md`

**Comment by TimTaylor** [comment]
closed by https://github.com/reconverse/reportfactory/commit/64ed650649ecc7fa6c1acc343ec607811a2a296e
